services:
  - type: web
    name: etude-line
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: DATABASE_URL
        fromDatabase:
          name: etude-line-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: etude-line-db
    databaseName: etude_line
    user: etude_line_admin
    region: oregon
    plan: free
