services:
  - type: web
    name: etude-line
    env: python
    region: oregon
    plan: pro  # REQUIS pour 100k users (8GB RAM, 4 vCPU, 100+ connections)
    buildCommand: pip install -r requirements.txt
    # ⚡ OPTIMISATION: Gunicorn avec 8 workers pour gérer 200+ utilisateurs simultanés
    # Chaque worker = 25-30 utilisateurs → 8 workers = 200-240 utilisateurs simultanés
    # CRITIQUE pour 100k utilisateurs (1% en ligne = 1000 utilisateurs simultanés)
    startCommand: gunicorn main:app --workers 8 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --max-requests 1000 --max-requests-jitter 50
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: DATABASE_URL
        fromDatabase:
          name: etude-line-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: etude-line-db
    databaseName: etude_line
    user: etude_line_admin
    region: oregon
    plan: pro  # REQUIS pour 100k users (256GB storage, 120 connections, backups)
