services:
  - type: web
    name: etude-line
    env: python
    region: oregon
    plan: free  # Démarrage gratuit (upgrader vers 'starter' à 500+ users, 'pro' à 5000+ users)
    buildCommand: pip install -r requirements.txt
    # Uvicorn simple pour plan FREE (upgrader vers Gunicorn multi-workers avec plan Starter/Pro)
    # Pour 500+ users: plan starter + workers 2
    # Pour 5000+ users: plan pro + workers 8 (voir OPTIMISATIONS_100K_UTILISATEURS.md)
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: DATABASE_URL
        fromDatabase:
          name: etude-line-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

databases:
  - name: etude-line-db
    databaseName: etude_line
    user: etude_line_admin
    region: oregon
    plan: free  # Démarrage gratuit (upgrader vers 'starter' à 500+ users, 'pro' à 5000+ users)
